name: "Plus"

author: "Duc Tri Le"

category: utilities

tags: [mutator, element, event, layer, autocomplete, tab, storage, chain, asset, popup]

current: 0.3.1

exports: "mootools-plus.js"

sources:
  - "source/Plus/Plus.js"
  - "source/Class/BindInstances.js"
  - "source/Class/Class.Mutators.Static.js"
  - "source/Class/Class.Mutators.StoredInstances.js"
  - "source/Class/HtmlOptions.js"
  - "source/Class/Singleton.js"
  - "source/Element/Element.Delegation.Plus.js"
  - "source/Element/Element.Plus.js"
  - "source/Interface/AutoComplete.js"
  - "source/Interface/Layer.js"
  - "source/Interface/Tab.js"
  - "source/Request/Responses.js"
  - "source/Types/Array.Plus.js"
  - "source/Types/Function.Plus.js"
  - "source/Types/Object.Plus.js"
  - "source/Types/String.Plus.js"
  - "source/Utilities/AssetManager.js"
  - "source/Utilities/Cookie.Plus.js"
  - "source/Utilities/NamedChain.js"
  - "source/Utilities/Popup.js"
  - "source/Utilities/Storages.js"
