name: "Plus"

exports: "mootools-plus.js"

sources:
  - "source/Plus/Plus.js"
  - "source/Class/BindInstances.js"
  - "source/Class/Class.Static.js"
  - "source/Class/StoredInstances.js"
  - "source/Element/Element.Delegation.Plus.js"
  - "source/Element/Element.Plus.js"
  - "source/Request/Responses.js"
  - "source/Types/Array.Plus.js"
  - "source/Types/Function.Plus.js"
  - "source/Types/String.Plus.js"
  - "source/Utilities/Cookie.Plus.js"
  - "source/Utilities/HtmlOptions.js"
  - "source/Utilities/NamedChain.js"