name: "Plus"

exports: "mootools-plus.js"

sources:
  - "source/Plus/Plus.js"
  - "source/Class/BindInstances.js"
  - "source/Class/Class.Mutators.Static.js"
  - "source/Class/Class.Mutators.StoredInstances.js"
  - "source/Class/HtmlOptions.js"
  - "source/Element/Element.Delegation.Plus.js"
  - "source/Element/Element.Plus.js"
  - "source/Interface/Layer.js"
  - "source/Request/Responses.js"
  - "source/Types/Array.Plus.js"
  - "source/Types/Function.Plus.js"
  - "source/Types/String.Plus.js"
  - "source/Utilities/Cookie.Plus.js"
  - "source/Utilities/NamedChain.js"